host: localhost:8080
info:
  contact: {}
  title: Go-pingpong Swagger API
  version: 1.0.0
paths:
  /users:
    get:
      consumes:
      - application/json
      description: ddd
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Pong
swagger: "2.0"
